export const allItems = [
  { id: "1", title: "Automotive" },
  { id: "2", title: "Baby" },
  { id: "3", title: "Beauty & Personal Care" },
  { id: "4", title: "Books" },
  { id: "5", title: "Boy's Fashion" },
  { id: "6", title: "Computers" },
  { id: "7", title: "Deals" },
  { id: "8", title: "Digital Music" },
  { id: "9", title: "Electronics" },
  { id: "10", title: "Girls Fashion" },
  { id: "11", title: "Health & Household" },
  { id: "12", title: "Home & Kitchen" },
  { id: "13", title: "Kindle Store" },
  { id: "14", title: "Luggage" },
  { id: "15", title: "Men's Fashion" },
  { id: "16", title: "Movies & TV" },
  { id: "17", title: "Music, CDs & Vinyl" },
  { id: "18", title: "Pet Supplies" },
  { id: "19", title: "Prime Video" },
  { id: "20", title: "Software" },
  { id: "21", title: "Sports & Outdoors" },
  { id: "22", title: "Tools & Home Improvement" },
  { id: "23", title: "Toys & Games" },
  { id: "24", title: "Video Games" },
  { id: "25", title: "Women's Fashion" },
];
